-- Session 2
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION;
UPDATE Schedule SET Coupons = 7 WHERE ID = 1;
COMMIT TRANSACTION;
SELECT * FROM Schedule WHERE ID = 1;
ROLLBACK TRANSACTION;

--грязное чтение
-- Session 2
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM Schedule WHERE ID = 1;

-- Read Commited
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
UPDATE Schedule SET Coupons = 7 WHERE ID = 1;
COMMIT TRANSACTION;

-- Repeateble read
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION;
UPDATE Schedule SET Coupons = 7 WHERE ID = 1;
COMMIT TRANSACTION;

-- Phantom
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION;
INSERT INTO Schedule (DoctorID, [Day of week], Coupons, [Reception time])
VALUES (2, 'Tuesday', 15, '10:00-13:00');
COMMIT TRANSACTION;

-- Phantom serialized
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;
INSERT INTO Schedule (DoctorID, [Day of week], Coupons, [Reception time])
VALUES (2, 'Tuesday', 15, '11:00-13:00');
COMMIT TRANSACTION;